#!/usr/bin/env bash

QGIS_IMAGE=qgis/qgis

QGIS_IMAGE_latest=latest
QGIS_IMAGE_V_3_26=release-3_26

QGIS_VERSION_TAGS=($QGIS_IMAGE_latest $QGIS_IMAGE_V_3_26)

export IMAGE=$QGIS_IMAGE

for TAG in "${QGIS_VERSION_TAGS[@]}"
do
    echo "Running tests for QGIS $TAG"
    export QGIS_VERSION_TAG=$TAG
    export WITH_PYTHON_PEP=false
    export ON_TRAVIS=false
    export MUTE_LOGS=true

    docker-compose up -d

    sleep 10

    docker-compose exec -T qgis-testing-environment qgis_testrunner.sh test_suite.test_package

    # Removing the autogenerated .pyc, .pyo and __pycache__ files that were created during running tests,
    docker-compose exec -T qgis-testing-environment sh -c 'find . -type f -name "*.py[c|o]" -delete'
    docker-compose exec -T qgis-testing-environment sh -c 'find . -type d -name "__pycache__" -delete'
    docker-compose exec -T qgis-testing-environment sh -c 'find . -type f -name "*.tif.aux.xml" -delete'

    docker-compose down

done
